
meta_product_name: "EMDR BAS-RHIN"
meta_title: "EMDR BAS-RHIN"
meta_description: "Cabinet de Mr GRAVE"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
